### ISSUE TITLE
Running e2e locally on any view except NYU fails

### ISSUE THREAD

**Issue by barnabyalter** [NYULibraries/primo-explore-views#85]
@etgrieco  I.e. `VIEW=NYUAD docker-compose run e2e` fails for me because the actual results are using the `NYU` view, not `${VIEW}`

Do I have this syntax correct?

**Comment by etgrieco** [comment]
I just retried on my computer and am seeing it pass okay; my current hypothesis is that `docker-compose down` wasn't performed between tests, since it requires spinning up a brand new container in order to compile and serve the appropriate development view package. I remember seeing this issue when setting up my script. Is this possibly why it was always running against the `NYU` server?

**Comment by barnabyalter** [comment]
Worked. Closing.
